[category]
 name = "electric_load"
 description = "mwh for zones in iso or rto"

# [jar_config]
#  flag = "deprecated"
#  address = "\"Scala-http/classes/artifacts/scalahttp_jar/*\""
#  comments = """escape the quotation mark as the path will be passed to the command line arguments and in case of spaces
#   in the path"""

[site]
 timezone = "US/Eastern"
 state = "NY"
 base_folder = "/Users/limingzhou/zhoul/work/energy/sites/albany-test"
 name = "Albany-NY"
 alias = "albany-test"
 sql_location = "CAPITL"
 site_folder = "nyiso"
 #center[lon, lat]
 center = [-73.0, 43.0]
 #[east, west, south, north]
 rect = [50.0, 50.0, 50.0, 50.0]
 t0="2018-01-01"
 t1="2018-01-04"
 hrrr_paras_file = "/Users/limingzhou/zhoul/work/energy/pytools/pytools/data_prep/hrrr_paras_pynio.txt"
 description = "Zone Capital of NYISO"
 comments = """name is used for database query and must match what the database use; while alias is used for setting up
  the folder structure"""
 #envtest = "$ENV_TEST"

[load]
 schema = "iso"
 table = "nyiso_hist_load"
 table_iso_fst = "nyiso_fst_load"
 table_our_fst = "nyiso_fst_load_ours"
 unit = "mwh"
 datetime_column = "timestamp"
 daylightsaving_col = "daylightsaving"
 load_column = "load"
 sql_template_file = "sql_template/nyiso_sql_template.toml"
 #reasonable value range limit
 limit = [0, 99999]
 lag_hours = 168
 utc_to_local_hours = -5
 load_lag_start = 72

[weather]
hist_weather_pickle = "../data/grib2_folder_0.pkl"
folder_col_name = "folder"
filename_col_name = "filename"
type_col_name = "type"

hrrr_hist = ["utah"] #["hrrr2", "utah"]
hrrr_predict = ["hrrr_fst"]

[model]
y_label = "load"
models = [ {ahead=1, uri="file:///Users/limingzhou/zhoul/work/me/xaog_proj/src/python/pytools/pytools/modeling/mlruns/7831ce8125a240cdb0c7769ab0b92311/artifacts/Albany-NY-fst-1-full"},
 {ahead=6, uri="file:///Users/limingzhou/zhoul/work/me/xaog_proj/src/python/pytools/pytools/modeling/mlruns/b4aaa0b068404188865c289d270a0b80/artifacts/Albany-NY-fst-6"} ]