[category]
 name = "electric_load"
 description = "mwh for zones in iso or rto"

[site]
 timezone = "US/Eastern"
 state = "NY"
 base_folder = "~/zhoul/work/energy/sites/albany-test"
 name = "Albany-NY"
 alias = "albany-test"
 sql_location = "CAPITL"
 back_fst_window = ["2020-01-01 00:00", "2025-01-01 00:00"]
 #site_folder = "nyiso"
 #center[lon, lat]
 center = [-73.0, 43.0]
 #[east, west, south, north]
 rect = [30.0, 30.0, 30.0, 30.0]
 t0="2018-11-03"
 t1="2018-11-05"
 description = "Zone Capital of NYISO"
 comments = """name is used for database query and must match what the database use; while alias is used for setting up
  the folder structure"""
 #envtest = "$ENV_TEST"

[load]
 db_name="daf"
 db_schema = "iso"
 table = "nyiso_hist_load"
 table_iso_fst = "nyiso_fst_load"
 table_our_fst = "nyiso_fst_load_ours"
 unit = "mwh"
 datetime_column = "timestamp"
 daylightsaving_col = "daylightsaving"
 load_column = "load"
 #relative to the config folder
 sql_template_file = "sql_template/nyiso_sql_template.toml"
 #reasonable value range limit
 limit = [0, 99999]
 lag_hours = 168
 utc_to_local_hours = -5
 fst_hours =[1, 6, 24]

[weather]
envelope = [1548, 1568, 774, 794]
hist_weather_pickle = "../data/grib2_folder_1.pkl"
fullfile_col_name = "full_file_name"
filename_col_name = "filename"
type_col_name = "type"
hrrr_paras_file = "data_prep/hrrr_paras_cfgrib.txt"

#hrrr_hist = ["utah"] #["hrrr2", "utah"]
hrrr_predict = "hrrr_fst"

[model]
y_label = "load"
forecast_horizon = [
    [1, 30],
    [25,48]
]
cv_settings = [
   ["2018-11-03","2018-11-04 12:00","2018-11-04 13:00","2018-11-05"]
    # ["2018-01-01", "2020-01-01", "2020-01-01", "2021-01-01"],
    # ["2020-01-01", "2021-01-01", "2021-01-01","2022-01-01"],
    # ["2021-01-01", "2022-01-01", "2022-01-01","2023-01-01"],
    # ["2022-01-01", "2023-01-01", "2023-01-01","2024-01-01"],
    # ["2023-01-01", "2024-01-01", "2024-01-01","2025-01-01"]
]
final_train_hist = ["2021-01-01", "2025-01-01"]
models = [ ]