[sql]

query_max_date = """
 select max(date_add("Time Stamp", interval \
 case when "Time Zone" = 'EDT' then -1 else 0 end hour)) as max_date from {table_name} \
 where "Name"='{site_name}' and "Integrated Load" is not null
"""

query_train = """
 SELECT timestamp, \
 case when "Time Zone" = 'EDT' then 1 else 0 end daylightsaving, \
 "Integrated Load" "load" \
 FROM {table_name} l \
 where "Name"='{site_name}' and timestamp between '{t0}' and '{t1}' \
 order by timestamp
"""

query_predict = """
 SELECT timestamp, \
 case when "Time Zone" = 'EDT' then 1 else 0 end daylightsaving, \
 "Integrated Load" "load"  \
 FROM {schema}.{table_name} l \
 where "Name"='{site_name}' and timestamp between '{t0}' and '{t1}' \
 union \
 select timestamp, \
 case when c.timestamp >= d.start and c.timestamp<d.end then 1 else   0 end daylightsaving, \
 null "load" \
 from calendar c join daylightsaving d on year(c.timestamp )=d.year \
 where c.timestamp > '{max_load_time}' and  c.timestamp <= '{t1}' \
 order by timestamp
"""