@startuml

top to bottom direction

class MlFlowConfig{
-address
-model_config
-modeling_setting
-weather_para
-__init__(address, model_config, modeling_setting, weather_para)
}

class MlFlowTrain{
-mlflow_config
-__init__(mlflow_config)
+build_model()
+register_model()
}

MlFlowConfig -up-* MlFlowTrain



@enduml